"""Publish the synth-only 24-point YOLO-pose model to the HuggingFace Hub.

A model repo paired with the synthetic dataset (same name, model type). This is
the model trained *entirely* on the synthetic City Sample frames - it shows the
24-point labels are clean and learnable in-domain, separate from the production
real-world model (kiselyovd/vehicle-keypoints).

    uv run python scripts/publish_synth_model_hf.py
"""

from __future__ import annotations

from pathlib import Path

from huggingface_hub import HfApi

REPO = "kiselyovd/citysample-vehicle-keypoints-24pt"  # model-type repo
WEIGHTS = Path("artifacts/synth24_runs/synth24/weights/best.pt")

CARD = """---
license: mit
library_name: ultralytics
pipeline_tag: keypoint-detection
tags:
  - ultralytics
  - yolo
  - yolo-pose
  - keypoint-detection
  - vehicle
  - synthetic
  - unreal-engine-5
  - city-sample
  - sim-to-real
datasets:
  - kiselyovd/citysample-vehicle-keypoints-24pt
base_model: Ultralytics/YOLO26
---

# City Sample Vehicle Keypoints - 24-point (synthetic-only)

A YOLO-pose model trained **entirely on synthetic data** - the
[City Sample 24-point vehicle-keypoint dataset](https://huggingface.co/datasets/kiselyovd/citysample-vehicle-keypoints-24pt)
rendered in Unreal Engine 5. It predicts a 24-point anatomical keypoint schema
(wheels, head/tail lights, exhaust, roof corners, center, mirrors, bumper and
window corners) plus a bounding box per vehicle.

Generated by [kiselyovd/ue5-vehicle-synth](https://github.com/kiselyovd/ue5-vehicle-synth).

## What this model is for

This is a **research / proof-of-concept** model that demonstrates the synthetic
dataset is clean and learnable: a model trained only on it localises vehicles and
their keypoints well on held-out synthetic frames. For real-world 14-point vehicle
keypoints, see the production model
[kiselyovd/vehicle-keypoints](https://huggingface.co/kiselyovd/vehicle-keypoints).

## In-domain results (held-out synthetic val)

| Metric | Box | Pose |
|---|---|---|
| mAP@50 | **0.859** | 0.331 |
| mAP@50-95 | 0.523 | 0.194 |

(Pose mAP is understated: ultralytics uses default OKS sigmas, which are tuned for
17-point human pose, not this 24-point vehicle schema.) Trained from
`yolo26n-pose` on 1,296 synthetic frames, 100 epochs, imgsz 480.

## Usage

```python
from huggingface_hub import hf_hub_download
from ultralytics import YOLO

w = hf_hub_download("kiselyovd/citysample-vehicle-keypoints-24pt", "best.pt")
model = YOLO(w)
results = model.predict("your_street_scene.jpg")
# results[0].keypoints.xy -> (N, 24, 2) keypoints per detected vehicle
```

## Honest caveats

- **Synthetic domain.** Trained only on rendered frames; expect a sim-to-real gap
  on real photos (no real images were used).
- **Evaluation.** Cross-evaluating against the real CarFusion dataset is confounded
  by CarFusion's own noisy, sparse 14-point labels - it conflates transfer quality
  with label-convention mismatch and is not a fair judge of this model. The
  in-domain numbers above and the dataset's pixel-exact construction are the honest
  signal of label quality.

## License

MIT for the weights. Rendered training frames come from Epic's City Sample under
the UE EULA (non-interactive renders are distributable; no Epic assets are shipped).
"""


def main() -> None:
    if not WEIGHTS.exists():
        raise SystemExit(f"weights not found: {WEIGHTS}")
    api = HfApi()
    api.create_repo(REPO, repo_type="model", exist_ok=True)
    card = Path("artifacts/synth24_runs/synth24/MODEL_CARD.md")
    card.write_text(CARD, encoding="utf-8")
    api.upload_file(
        path_or_fileobj=str(WEIGHTS),
        path_in_repo="best.pt",
        repo_id=REPO,
        repo_type="model",
        commit_message="Add synth-only 24-pt YOLO-pose weights",
    )
    api.upload_file(
        path_or_fileobj=str(card),
        path_in_repo="README.md",
        repo_id=REPO,
        repo_type="model",
        commit_message="Add model card",
    )
    print(f"published -> https://huggingface.co/{REPO}")


if __name__ == "__main__":
    main()
